FROM ekonomizer/golang
MAINTAINER Andrey Gorelov <ekonomizer@gmail.com>

ARG PORT
ARG REPO
ARG SERVER_EXEC
ARG RUNNER_REPO
ARG RUNNER_FILE

ENV PORT ${PORT}
ENV REPO ${REPO}
ENV SERVER_EXEC ${SERVER_EXEC}
WORKDIR /project/
EXPOSE ${PORT}

ADD ${RUNNER_REPO} /project
RUN unzip master.zip
RUN chmod 777 ${RUNNER_FILE}
#ENTRYPOINT ${RUNNER_FILE}