version: '2'

services:
  web_go:
    build:
      context: .
      args:
        REPO: github.com/ekonomizer/normalize_go
        SERVER_EXEC: /project/bin/normalize_go
        PORT: 12345
    ports:
     - "8880:12345"
    restart: always
